# Generated by Django 5.1.1 on 2024-09-25 14:08

from datetime import datetime, timezone
from django.db import migrations, models
import uuid

def loadRealEstateTypes(apps, schema_editor):
    RealEstateType = apps.get_model('realhomebackend', 'RealEstateType')
    RealEstateType.objects.create(Id= 'd9c67d92-5750-442f-984b-8f4f4c11a7e9', Name='HOUSE', DisplayName='House')
    RealEstateType.objects.create(Id= 'c77a64e0-6a62-48e0-ad4d-f425c0070d55', Name='APARTMENT', DisplayName='Apartment')
    RealEstateType.objects.create(Id= 'e1662fc7-bd8f-47e8-ac97-be4b1d3d0183', Name='TOWN_HOUSE', DisplayName='Town House')
    RealEstateType.objects.create(Id= 'deda5adc-a9e2-4eee-b11c-9157c1eaaa02', Name='FARM', DisplayName='Farm')

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstateType',
            fields=[
                ('Id', models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4())),
                ('Name', models.CharField(max_length=50)),
                ('DisplayName', models.CharField(max_length=100)),
                ('DateCreated', models.DateTimeField(default=datetime.now(timezone.utc))),
            ],
            options={'db_table': 'real_estate_types'}
        ),
        migrations.RunPython(loadRealEstateTypes)
    ]
