# Generated by Django 5.1.1 on 2024-10-10 16:00

from django.db import migrations, models
from datetime import datetime, timezone
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ('realhomebackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealEstate',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=500)),
                ('bathrooms', models.IntegerField(default=0)),
                ('bedrooms', models.IntegerField(default=0)),
                ('landSqm', models.IntegerField(default=0)),
                ('floorSqm', models.IntegerField(default=0)),
                ('parking', models.IntegerField(default=0)),
                ('shortDescription', models.CharField(max_length=250)),
                ('longDescription', models.CharField(max_length=5000)),
                ('dateCreated', models.DateTimeField(default=datetime.now(timezone.utc))),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realhomebackend.RealEstateType'))
            ],
            options={
                'db_table': 'real_estates',
            },
        ),
    ]
