# Generated by Django 5.1.1 on 2024-09-30 16:45

from django.db import migrations, models
import uuid

def AllRealEstateBuyProperties(apps, schema_editor):
    RealEstateType = apps.get_model('realhomebackend', 'All_RealEstate')
    RealEstateType.objects.create(Id= '', Title='HOUSE', Price='', City='', Suburb='',Zip_code='', Adress='')
    RealEstateType.objects.create(Id= '', Title='APARTMENT', Price='',City='',Suburb='',Zip_code='', Adress='')
    RealEstateType.objects.create(Id= '', Title='APARTMENT', Price='',City='',Suburb='',Zip_code='', Adress='')
    RealEstateType.objects.create(Id= '', Title='TOWN_HOUSE', Price='', City='',Suburb='',Zip_code='',Adress='')
    RealEstateType.objects.create(Id= '', Title='FARM', Price='', City='',Suburb='',Zip_code='', Adress='')
class Migration(migrations.Migration):

    dependencies = [
        ('realhomebackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_RealEstate_Buy',
            fields=[
                ('Id', models.UUIDField(primary_key=True, serialize=False, default=uuid.uuid4())),
                ('Title', models.CharField(max_length=200)),
                
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Address', models.CharField(max_length=255)),
                ('City', models.CharField(max_length=100)),
                ('Suburb', models.CharField(max_length=100)),
                ('Zip_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'All_RealEstate_Buy',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='allrealestatesbuy',
            options={'managed': False},
        ),
    ]
