# Generated by Django 5.1.1 on 2024-09-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realhomebackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('suburb', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'properties',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='realestatetype',
            options={'managed': False},
        ),
    ]
